### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by pkokate18** [spyros-lytras/dinuq#5]
Hi,
Thanks a lot for your program.
I have a fasta file which is giving the above error at the line 542 of the code.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pkokate/miniconda3/lib/python3.7/site-packages/dinuq/sdu.py", line 542, in SDU
    dint = str(sequ[d] + sequ[d+1])
IndexError: string index out of range

[melanogaster.txt](https://github.com/spyros-lytras/dinuq/files/4914435/melanogaster.txt)

Thanks for your help.

**Comment by spyros-lytras** [comment]
This error was caused by having stop codons or non-coding sequences in the fasta file provided. DinuQ v1.1.1 now has more thorough troubleshooting messages for identifying such problems in the dataset.

**Comment by pkokate18** [comment]
Hi,

I hope you are well.
Thanks for the update. I might be using it in the future.
Thank you for your help.

with best regards

yours sincerely,

Prajakta
